# Generated by Django 3.2.4 on 2021-06-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='scope',
            new_name='scopes',
        ),
    ]
