# Generated by Django 3.2.4 on 2021-06-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_scope_tags_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='scopes',
            field=models.ManyToManyField(related_name='tag', to='articles.Scopes'),
        ),
    ]
